[package]
name = "monetary"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = "1.37.1"
chrono = {version= "0.4.40", features=["serde"]}
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "money"
harness = false
